const fs = require('fs');

const contextPath = './src/context/LanguageContext.jsx';
let content = fs.readFileSync(contextPath, 'utf8');

const newTranslations = {
  EN: {
    exp_eyebrow: "OUR EXPERIENCES",
    exp_title_1: "Unforgettable ",
    exp_title_2: "Desert Adventures",
    exp_desc: "Discover a range of thrilling desert experiences, designed for adventure seekers of all levels. From dune buggies to dirt bikes, we have the perfect ride for you.",
    exp_card1_title: "Desert Safari Online Booking",
    exp_card1_desc: "Explore our Desert Safari Online Booking with Enduro Bike Dubai. Experience thrilling routes across Dubai's spectacular desert landscapes.",
    exp_card1_cta: "EXPLORE SAFARI TOURS",
    exp_card2_title: "Dune Buggy Dubai",
    exp_card2_desc: "Get ready for an awesome off-road ride with our Dune Buggy Dubai experience. Built for adventure, comfort, and unforgettable desert exploration.",
    exp_card2_cta: "EXPLORE BUGGY TOURS",
    exp_card3_title: "Dirt Bike Dubai",
    exp_card3_desc: "Ready for a thrilling adventure? Ride through Dubai's wild desert terrain, discover unique routes, and experience true off-road freedom.",
    exp_card3_cta: "EXPLORE BIKE TOURS",
    exp_card4_title: "Quad Biking Dubai",
    exp_card4_desc: "Feel the thrill with Quad Biking Dubai and our powerful quad bikes. Follow experienced guides through challenging dunes and tracks for an exhilarating desert journey.",
    exp_card4_cta: "EXPLORE QUAD TOURS",
    exp_card5_title: "Desert Safari Dubai",
    exp_card5_desc: "Immerse yourself in the beauty of the Arabian desert. From peaceful morning adventures to magical evening experiences, discover unforgettable moments in the heart of Dubai.",
    exp_card5_cta: "EXPLORE DESERT SAFARI",
    cta_eyebrow: "READY FOR YOUR NEXT",
    cta_title_1: "DESERT ",
    cta_title_2: "STORY?",
    cta_desc: "Ready for an unforgettable desert adventure? Book your ride now and immerse yourself in the heart-pounding excitement of Dubai's deserts with Enduro Bike Dubai. Let the journey begin!",
    cta_book: "BOOK NOW",
    cta_hand_1: "SAME",
    cta_hand_2: "DESERT.",
    cta_hand_3: "DIFFERENT",
    cta_hand_4: "STORIES."
  },
  ES: {
    exp_eyebrow: "NUESTRAS EXPERIENCIAS",
    exp_title_1: "Aventuras Inolvidables ",
    exp_title_2: "en el Desierto",
    exp_desc: "Descubre una gama de emocionantes experiencias en el desierto, diseñadas para buscadores de aventuras de todos los niveles.",
    exp_card1_title: "Reserva Safari en el Desierto",
    exp_card1_desc: "Explora nuestra reserva en línea de Safari en el Desierto con Enduro Bike Dubai. Experimenta rutas emocionantes.",
    exp_card1_cta: "EXPLORAR SAFARI",
    exp_card2_title: "Buggy en las Dunas",
    exp_card2_desc: "Prepárate para un increíble viaje todoterreno con nuestra experiencia Dune Buggy Dubai.",
    exp_card2_cta: "EXPLORAR BUGGIES",
    exp_card3_title: "Moto de Cross Dubai",
    exp_card3_desc: "Recorre el terreno salvaje del desierto de Dubái, descubre rutas únicas.",
    exp_card3_cta: "EXPLORAR MOTOS",
    exp_card4_title: "Quads Dubai",
    exp_card4_desc: "Siente la emoción con Quad Biking Dubai y nuestros potentes quads.",
    exp_card4_cta: "EXPLORAR QUADS",
    exp_card5_title: "Safari en el Desierto",
    exp_card5_desc: "Sumérgete en la belleza del desierto árabe. Momentos inolvidables.",
    exp_card5_cta: "EXPLORAR SAFARI",
    cta_eyebrow: "¿LISTO PARA TU PRÓXIMA",
    cta_title_1: "HISTORIA ",
    cta_title_2: "EN EL DESIERTO?",
    cta_desc: "¿Listo para una aventura inolvidable? Reserva tu viaje ahora.",
    cta_book: "RESERVAR AHORA",
    cta_hand_1: "MISMO",
    cta_hand_2: "DESIERTO.",
    cta_hand_3: "DIFERENTES",
    cta_hand_4: "HISTORIAS."
  },
  RU: {
    exp_eyebrow: "НАШИ ВПЕЧАТЛЕНИЯ",
    exp_title_1: "Незабываемые ",
    exp_title_2: "Приключения",
    exp_desc: "Откройте для себя спектр захватывающих впечатлений в пустыне.",
    exp_card1_title: "Онлайн-бронирование сафари",
    exp_card1_desc: "Исследуйте наше онлайн-бронирование сафари по пустыне.",
    exp_card1_cta: "ИССЛЕДОВАТЬ САФАРИ",
    exp_card2_title: "Багги по Дюнам Дубая",
    exp_card2_desc: "Приготовьтесь к потрясающей поездке по бездорожью на багги.",
    exp_card2_cta: "ИССЛЕДОВАТЬ БАГГИ",
    exp_card3_title: "Кроссовые мотоциклы Дубай",
    exp_card3_desc: "Прокатитесь по дикой пустыне Дубая на кроссовом мотоцикле.",
    exp_card3_cta: "ИССЛЕДОВАТЬ МОТОЦИКЛЫ",
    exp_card4_title: "Квадроциклы Дубай",
    exp_card4_desc: "Почувствуйте острые ощущения от катания на квадроциклах.",
    exp_card4_cta: "ИССЛЕДОВАТЬ КВАДРОЦИКЛЫ",
    exp_card5_title: "Сафари по Пустыне Дубай",
    exp_card5_desc: "Погрузитесь в красоту арабской пустыни.",
    exp_card5_cta: "ИССЛЕДОВАТЬ САФАРИ",
    cta_eyebrow: "ГОТОВЫ К НОВОЙ",
    cta_title_1: "ИСТОРИИ ",
    cta_title_2: "В ПУСТЫНЕ?",
    cta_desc: "Готовы к незабываемым приключениям? Бронируйте поездку прямо сейчас.",
    cta_book: "ЗАБРОНИРОВАТЬ",
    cta_hand_1: "ТА ЖЕ",
    cta_hand_2: "ПУСТЫНЯ.",
    cta_hand_3: "ДРУГИЕ",
    cta_hand_4: "ИСТОРИИ."
  },
  FR: {
    exp_eyebrow: "NOS EXPÉRIENCES",
    exp_title_1: "Aventures Inoubliables ",
    exp_title_2: "dans le Désert",
    exp_desc: "Découvrez une gamme d'expériences palpitantes dans le désert.",
    exp_card1_title: "Réservation de Safari en Ligne",
    exp_card1_desc: "Explorez notre réservation en ligne de safari dans le désert.",
    exp_card1_cta: "EXPLORER SAFARI",
    exp_card2_title: "Buggy dans les Dunes",
    exp_card2_desc: "Préparez-vous pour une balade hors route impressionnante.",
    exp_card2_cta: "EXPLORER BUGGIES",
    exp_card3_title: "Motocross Dubaï",
    exp_card3_desc: "Roulez sur le terrain sauvage du désert de Dubaï.",
    exp_card3_cta: "EXPLORER MOTOS",
    exp_card4_title: "Quad Dubaï",
    exp_card4_desc: "Ressentez le frisson avec nos puissants quads.",
    exp_card4_cta: "EXPLORER QUADS",
    exp_card5_title: "Safari dans le Désert Dubaï",
    exp_card5_desc: "Plongez-vous dans la beauté du désert d'Arabie.",
    exp_card5_cta: "EXPLORER SAFARI",
    cta_eyebrow: "PRÊT POUR VOTRE PROCHAINE",
    cta_title_1: "HISTOIRE ",
    cta_title_2: "DANS LE DÉSERT ?",
    cta_desc: "Prêt pour une aventure inoubliable ? Réservez votre balade maintenant.",
    cta_book: "RÉSERVER",
    cta_hand_1: "MÊME",
    cta_hand_2: "DÉSERT.",
    cta_hand_3: "HISTOIRES",
    cta_hand_4: "DIFFÉRENTES."
  },
  AR: {
    exp_eyebrow: "تجاربنا",
    exp_title_1: "مغامرات صحراوية ",
    exp_title_2: "لا تنسى",
    exp_desc: "اكتشف مجموعة من التجارب الصحراوية المثيرة.",
    exp_card1_title: "حجز سفاري صحراوي",
    exp_card1_desc: "استكشف حجز رحلات السفاري الصحراوية عبر الإنترنت.",
    exp_card1_cta: "اكتشف رحلات السفاري",
    exp_card2_title: "عربات الكثبان دبي",
    exp_card2_desc: "استعد لرحلة رائعة على الطرق الوعرة.",
    exp_card2_cta: "اكتشف رحلات الباغي",
    exp_card3_title: "دراجات نارية دبي",
    exp_card3_desc: "اركب عبر تضاريس الصحراء البرية في دبي.",
    exp_card3_cta: "اكتشف رحلات الدراجات",
    exp_card4_title: "دراجات رباعية دبي",
    exp_card4_desc: "اشعر بالإثارة مع الدراجات الرباعية القوية.",
    exp_card4_cta: "اكتشف رحلات الدراجات الرباعية",
    exp_card5_title: "سفاري صحراوي دبي",
    exp_card5_desc: "انغمس في جمال الصحراء العربية.",
    exp_card5_cta: "اكتشف السفاري",
    cta_eyebrow: "هل أنت مستعد",
    cta_title_1: "لقصتك ",
    cta_title_2: "التالية؟",
    cta_desc: "هل أنت مستعد لمغامرة لا تنسى؟ احجز رحلتك الآن.",
    cta_book: "احجز الآن",
    cta_hand_1: "نفس",
    cta_hand_2: "الصحراء.",
    cta_hand_3: "قصص",
    cta_hand_4: "مختلفة."
  }
};

for (const lang in newTranslations) {
  const translations = newTranslations[lang];
  let block = '';
  for (const [key, val] of Object.entries(translations)) {
      block += `,\n    ${key}: "${val}"`;
  }
  
  // Find where this lang block ends and insert
  const regex = new RegExp(`(${lang}:\\s*{[\\s\\S]*?)(})`);
  content = content.replace(regex, `$1${block}\n  $2`);
}

fs.writeFileSync(contextPath, content);
