import React, { createContext, useState, useContext } from 'react';

export const languages = [
  { code: 'EN', name: 'English', flag: 'GB' },
  { code: 'ES', name: 'Español', flag: 'ES' },
  { code: 'RU', name: 'Русский', flag: 'RU' },
  { code: 'FR', name: 'Français', flag: 'FR' },
  { code: 'AR', name: 'العربية', flag: 'AE' }
];

const LanguageContext = createContext();

const translations = {
  EN: {
    home: "HOME",
    about: "ABOUT US",
    packages: "PACKAGES",
    contact: "CONTACT",
    book: "BOOK YOUR RIDE",
    hero_line1: "RIDE BEYOND",
    hero_line2: "THE ROAD",
    hero_desc: "Dirt bikes. Buggies. Quads. One desert built for adrenaline.",
    explore_rides: "EXPLORE RIDES",
    explore: "Explore",
    our_tours: "Our Tours",
    our_packages: "OUR PACKAGES",
    quick_links: "QUICK LINKS",
    experiences: "EXPERIENCES",
    contact_us: "CONTACT US",
    follow: "FOLLOW THE ADVENTURE",
    exp_1_title: "KTM 450CC",
    exp_1_sub: "Pro-Grade Bikes",
    exp_2_title: "Guided Desert Rides",
    exp_2_sub: "Expert Local Guides",
    exp_3_title: "All Gear Included",
    exp_3_sub: "Ride Safe. Ride Bold.",
    about_eyebrow: "OUR STORY",
    about_title_1: "MORE THAN",
    about_title_2: "A RIDE.",
    about_title_3: "IT'S AN",
    about_title_4: "ADVENTURE.",
    about_desc: "Born in the Dubai desert, Enduro Bike Dubai is built around one simple idea — to turn every ride into a story worth remembering.",
    about_loc: "AL BADAYER DESERT · DUBAI",
    about_btn: "DISCOVER OUR STORY",
    about_feat1_title: "BORN IN DUBAI",
    about_feat1_sub: "Desert roots.",
    about_feat2_title: "BUILT FOR ADVENTURE",
    about_feat2_sub: "More than a tour.",
    about_feat3_title: "RIDE WITH CONFIDENCE",
    about_feat3_sub: "Guided. Equipped. Ready."
  ,
    exp_eyebrow: "OUR EXPERIENCES",
    exp_title_1: "Unforgettable ",
    exp_title_2: "Desert Adventures",
    exp_desc: "Discover a range of thrilling desert experiences, designed for adventure seekers of all levels. From dune buggies to dirt bikes, we have the perfect ride for you.",
    exp_card1_title: "Desert Safari Online Booking",
    exp_card1_desc: "Explore our Desert Safari Online Booking with Enduro Bike Dubai. Experience thrilling routes across Dubai's spectacular desert landscapes.",
    exp_card1_cta: "EXPLORE SAFARI TOURS",
    exp_card2_title: "Dune Buggy Dubai",
    exp_card2_desc: "Get ready for an awesome off-road ride with our Dune Buggy Dubai experience. Built for adventure, comfort, and unforgettable desert exploration.",
    exp_card2_cta: "EXPLORE BUGGY TOURS",
    exp_card3_title: "Dirt Bike Dubai",
    exp_card3_desc: "Ready for a thrilling adventure? Ride through Dubai's wild desert terrain, discover unique routes, and experience true off-road freedom.",
    exp_card3_cta: "EXPLORE BIKE TOURS",
    exp_card4_title: "Quad Biking Dubai",
    exp_card4_desc: "Feel the thrill with Quad Biking Dubai and our powerful quad bikes. Follow experienced guides through challenging dunes and tracks for an exhilarating desert journey.",
    exp_card4_cta: "EXPLORE QUAD TOURS",
    exp_card5_title: "Desert Safari Dubai",
    exp_card5_desc: "Immerse yourself in the beauty of the Arabian desert. From peaceful morning adventures to magical evening experiences, discover unforgettable moments in the heart of Dubai.",
    exp_card5_cta: "EXPLORE DESERT SAFARI",
    cta_eyebrow: "READY FOR YOUR NEXT",
    cta_title_1: "DESERT ",
    cta_title_2: "STORY?",
    cta_desc: "Ready for an unforgettable desert adventure? Book your ride now and immerse yourself in the heart-pounding excitement of Dubai's deserts with Enduro Bike Dubai. Let the journey begin!",
    cta_book: "BOOK NOW",
    cta_hand_1: "SAME",
    cta_hand_2: "DESERT.",
    cta_hand_3: "DIFFERENT",
    cta_hand_4: "STORIES."
  ,
    packages_eyebrow: "CHOOSE YOUR RIDE",
    packages_title_1: "PREMIUM",
    packages_title_2: "DESERT",
    packages_title_3: "PACKAGES",
    packages_desc: "From high-speed dirt bikes to rugged dune buggies and powerful quads, we have the perfect machine for your next adventure."
  },
  ES: {
    home: "INICIO",
    about: "SOBRE NOSOTROS",
    packages: "PAQUETES",
    contact: "CONTACTO",
    book: "RESERVAR AHORA",
    hero_line1: "MÁS ALLÁ DE",
    hero_line2: "LA CARRETERA",
    hero_desc: "Motos de cross. Buggies. Quads. Un desierto construido para la adrenalina.",
    explore_rides: "EXPLORAR RUTAS",
    explore: "Explorar",
    our_tours: "Nuestras Rutas",
    our_packages: "NUESTROS PAQUETES",
    quick_links: "ENLACES RÁPIDOS",
    experiences: "EXPERIENCIAS",
    contact_us: "CONTÁCTENOS",
    follow: "SÍGUENOS",
    exp_1_title: "KTM 450CC",
    exp_1_sub: "Motos de Nivel Profesional",
    exp_2_title: "Rutas Guiadas por el Desierto",
    exp_2_sub: "Guías Locales Expertos",
    exp_3_title: "Todo el Equipo Incluido",
    exp_3_sub: "Conduce Seguro. Conduce Valiente.",
    about_eyebrow: "NUESTRA HISTORIA",
    about_title_1: "MÁS QUE",
    about_title_2: "UN VIAJE.",
    about_title_3: "ES UNA",
    about_title_4: "AVENTURA.",
    about_desc: "Nacida en el desierto de Dubái, Enduro Bike Dubai se basa en una idea simple: convertir cada viaje en una historia digna de recordar.",
    about_loc: "DESIERTO DE AL BADAYER · DUBÁI",
    about_btn: "DESCUBRE NUESTRA HISTORIA",
    about_feat1_title: "NACIDO EN DUBÁI",
    about_feat1_sub: "Raíces en el desierto.",
    about_feat2_title: "CONSTRUIDO PARA LA AVENTURA",
    about_feat2_sub: "Más que un tour.",
    about_feat3_title: "CONDUCE CON CONFIANZA",
    about_feat3_sub: "Guiado. Equipado. Listo."
  ,
    exp_eyebrow: "NUESTRAS EXPERIENCIAS",
    exp_title_1: "Aventuras Inolvidables ",
    exp_title_2: "en el Desierto",
    exp_desc: "Descubre una gama de emocionantes experiencias en el desierto, diseñadas para buscadores de aventuras de todos los niveles.",
    exp_card1_title: "Reserva Safari en el Desierto",
    exp_card1_desc: "Explora nuestra reserva en línea de Safari en el Desierto con Enduro Bike Dubai. Experimenta rutas emocionantes.",
    exp_card1_cta: "EXPLORAR SAFARI",
    exp_card2_title: "Buggy en las Dunas",
    exp_card2_desc: "Prepárate para un increíble viaje todoterreno con nuestra experiencia Dune Buggy Dubai.",
    exp_card2_cta: "EXPLORAR BUGGIES",
    exp_card3_title: "Moto de Cross Dubai",
    exp_card3_desc: "Recorre el terreno salvaje del desierto de Dubái, descubre rutas únicas.",
    exp_card3_cta: "EXPLORAR MOTOS",
    exp_card4_title: "Quads Dubai",
    exp_card4_desc: "Siente la emoción con Quad Biking Dubai y nuestros potentes quads.",
    exp_card4_cta: "EXPLORAR QUADS",
    exp_card5_title: "Safari en el Desierto",
    exp_card5_desc: "Sumérgete en la belleza del desierto árabe. Momentos inolvidables.",
    exp_card5_cta: "EXPLORAR SAFARI",
    cta_eyebrow: "¿LISTO PARA TU PRÓXIMA",
    cta_title_1: "HISTORIA ",
    cta_title_2: "EN EL DESIERTO?",
    cta_desc: "¿Listo para una aventura inolvidable? Reserva tu viaje ahora.",
    cta_book: "RESERVAR AHORA",
    cta_hand_1: "MISMO",
    cta_hand_2: "DESIERTO.",
    cta_hand_3: "DIFERENTES",
    cta_hand_4: "HISTORIAS."
  ,
    packages_eyebrow: "ELIGE TU VIAJE",
    packages_title_1: "PAQUETES",
    packages_title_2: "PREMIUM",
    packages_title_3: "DEL DESIERTO",
    packages_desc: "Desde motos de cross de alta velocidad hasta buggies y potentes quads, tenemos la máquina perfecta para tu próxima aventura."
  },
  RU: {
    home: "ГЛАВНАЯ",
    about: "О НАС",
    packages: "ПАКЕТЫ",
    contact: "КОНТАКТЫ",
    book: "ЗАБРОНИРОВАТЬ",
    hero_line1: "ЗА ПРЕДЕЛАМИ",
    hero_line2: "ДОРОГИ",
    hero_desc: "Кроссовые мотоциклы. Багги. Квадроциклы. Одна пустыня, созданная для адреналина.",
    explore_rides: "ИССЛЕДОВАТЬ ПОЕЗДКИ",
    explore: "Исследовать",
    our_tours: "Наши Туры",
    our_packages: "НАШИ ПАКЕТЫ",
    quick_links: "БЫСТРЫЕ ССЫЛКИ",
    experiences: "ВПЕЧАТЛЕНИЯ",
    contact_us: "СВЯЗАТЬСЯ С НАМИ",
    follow: "СЛЕДИТЕ ЗА НАМИ",
    exp_1_title: "KTM 450CC",
    exp_1_sub: "Профессиональные Мотоциклы",
    exp_2_title: "Поездки с Гидом в Пустыне",
    exp_2_sub: "Местные Эксперты",
    exp_3_title: "Вся Экипировка Включена",
    exp_3_sub: "Катайтесь Безопасно. Катайтесь Смело.",
    about_eyebrow: "НАША ИСТОРИЯ",
    about_title_1: "БОЛЬШЕ ЧЕМ",
    about_title_2: "ПОЕЗДКА.",
    about_title_3: "ЭТО",
    about_title_4: "ПРИКЛЮЧЕНИЕ.",
    about_desc: "Enduro Bike Dubai, родившаяся в пустыне Дубая, основана на простой идее — превратить каждую поездку в историю, которую стоит помнить.",
    about_loc: "ПУСТЫНЯ АЛЬ-БАДАЙЕР · ДУБАЙ",
    about_btn: "УЗНАЙТЕ НАШУ ИСТОРИЮ",
    about_feat1_title: "РОЖДЕН В ДУБАЕ",
    about_feat1_sub: "Корни в пустыне.",
    about_feat2_title: "СОЗДАН ДЛЯ ПРИКЛЮЧЕНИЙ",
    about_feat2_sub: "Больше, чем тур.",
    about_feat3_title: "КАТАЙТЕСЬ УВЕРЕННО",
    about_feat3_sub: "С гидом. С экипировкой. Готовы."
  ,
    exp_eyebrow: "НАШИ ВПЕЧАТЛЕНИЯ",
    exp_title_1: "Незабываемые ",
    exp_title_2: "Приключения",
    exp_desc: "Откройте для себя спектр захватывающих впечатлений в пустыне.",
    exp_card1_title: "Онлайн-бронирование сафари",
    exp_card1_desc: "Исследуйте наше онлайн-бронирование сафари по пустыне.",
    exp_card1_cta: "ИССЛЕДОВАТЬ САФАРИ",
    exp_card2_title: "Багги по Дюнам Дубая",
    exp_card2_desc: "Приготовьтесь к потрясающей поездке по бездорожью на багги.",
    exp_card2_cta: "ИССЛЕДОВАТЬ БАГГИ",
    exp_card3_title: "Кроссовые мотоциклы Дубай",
    exp_card3_desc: "Прокатитесь по дикой пустыне Дубая на кроссовом мотоцикле.",
    exp_card3_cta: "ИССЛЕДОВАТЬ МОТОЦИКЛЫ",
    exp_card4_title: "Квадроциклы Дубай",
    exp_card4_desc: "Почувствуйте острые ощущения от катания на квадроциклах.",
    exp_card4_cta: "ИССЛЕДОВАТЬ КВАДРОЦИКЛЫ",
    exp_card5_title: "Сафари по Пустыне Дубай",
    exp_card5_desc: "Погрузитесь в красоту арабской пустыни.",
    exp_card5_cta: "ИССЛЕДОВАТЬ САФАРИ",
    cta_eyebrow: "ГОТОВЫ К НОВОЙ",
    cta_title_1: "ИСТОРИИ ",
    cta_title_2: "В ПУСТЫНЕ?",
    cta_desc: "Готовы к незабываемым приключениям? Бронируйте поездку прямо сейчас.",
    cta_book: "ЗАБРОНИРОВАТЬ",
    cta_hand_1: "ТА ЖЕ",
    cta_hand_2: "ПУСТЫНЯ.",
    cta_hand_3: "ДРУГИЕ",
    cta_hand_4: "ИСТОРИИ."
  ,
    packages_eyebrow: "ВЫБЕРИТЕ СВОЙ ТРАНСПОРТ",
    packages_title_1: "ПРЕМИАЛЬНЫЕ",
    packages_title_2: "ПАКЕТЫ",
    packages_title_3: "В ПУСТЫНЕ",
    packages_desc: "От скоростных кроссовых мотоциклов до багги и мощных квадроциклов — у нас есть идеальная машина для вашего следующего приключения."
  },
  FR: {
    home: "ACCUEIL",
    about: "À PROPOS",
    packages: "FORFAITS",
    contact: "CONTACT",
    book: "RÉSERVER",
    hero_line1: "AU-DELÀ DE",
    hero_line2: "LA ROUTE",
    hero_desc: "Motos tout-terrain. Buggies. Quads. Un désert construit pour l'adrénaline.",
    explore_rides: "EXPLORER LES BALADES",
    explore: "Explorer",
    our_tours: "Nos Tours",
    our_packages: "NOS FORFAITS",
    quick_links: "LIENS RAPIDES",
    experiences: "EXPÉRIENCES",
    contact_us: "NOUS CONTACTER",
    follow: "SUIVEZ L'AVENTURE",
    exp_1_title: "KTM 450CC",
    exp_1_sub: "Motos de Qualité Pro",
    exp_2_title: "Randonnées Guidées dans le Désert",
    exp_2_sub: "Guides Locaux Experts",
    exp_3_title: "Tout l'Équipement Inclus",
    exp_3_sub: "Roulez en Sécurité. Roulez Fort.",
    about_eyebrow: "NOTRE HISTOIRE",
    about_title_1: "PLUS QU'UNE",
    about_title_2: "BALADE.",
    about_title_3: "C'EST UNE",
    about_title_4: "AVENTURE.",
    about_desc: "Née dans le désert de Dubaï, Enduro Bike Dubai repose sur une idée simple : faire de chaque trajet une histoire mémorable.",
    about_loc: "DÉSERT D'AL BADAYER · DUBAÏ",
    about_btn: "DÉCOUVREZ NOTRE HISTOIRE",
    about_feat1_title: "NÉ À DUBAÏ",
    about_feat1_sub: "Racines dans le désert.",
    about_feat2_title: "CONÇU POUR L'AVENTURE",
    about_feat2_sub: "Plus qu'une visite.",
    about_feat3_title: "ROULEZ EN CONFIANCE",
    about_feat3_sub: "Guidé. Équipé. Prêt."
  ,
    exp_eyebrow: "NOS EXPÉRIENCES",
    exp_title_1: "Aventures Inoubliables ",
    exp_title_2: "dans le Désert",
    exp_desc: "Découvrez une gamme d'expériences palpitantes dans le désert.",
    exp_card1_title: "Réservation de Safari en Ligne",
    exp_card1_desc: "Explorez notre réservation en ligne de safari dans le désert.",
    exp_card1_cta: "EXPLORER SAFARI",
    exp_card2_title: "Buggy dans les Dunes",
    exp_card2_desc: "Préparez-vous pour une balade hors route impressionnante.",
    exp_card2_cta: "EXPLORER BUGGIES",
    exp_card3_title: "Motocross Dubaï",
    exp_card3_desc: "Roulez sur le terrain sauvage du désert de Dubaï.",
    exp_card3_cta: "EXPLORER MOTOS",
    exp_card4_title: "Quad Dubaï",
    exp_card4_desc: "Ressentez le frisson avec nos puissants quads.",
    exp_card4_cta: "EXPLORER QUADS",
    exp_card5_title: "Safari dans le Désert Dubaï",
    exp_card5_desc: "Plongez-vous dans la beauté du désert d'Arabie.",
    exp_card5_cta: "EXPLORER SAFARI",
    cta_eyebrow: "PRÊT POUR VOTRE PROCHAINE",
    cta_title_1: "HISTOIRE ",
    cta_title_2: "DANS LE DÉSERT ?",
    cta_desc: "Prêt pour une aventure inoubliable ? Réservez votre balade maintenant.",
    cta_book: "RÉSERVER",
    cta_hand_1: "MÊME",
    cta_hand_2: "DÉSERT.",
    cta_hand_3: "HISTOIRES",
    cta_hand_4: "DIFFÉRENTES."
  ,
    packages_eyebrow: "CHOISISSEZ VOTRE MONTURE",
    packages_title_1: "FORFAITS",
    packages_title_2: "DÉSERT",
    packages_title_3: "PREMIUM",
    packages_desc: "Des motos de cross à grande vitesse aux buggys et quads puissants, nous avons la machine parfaite pour votre prochaine aventure."
  },
  AR: {
    home: "الرئيسية",
    about: "معلومات عنا",
    packages: "الباقات",
    contact: "اتصل بنا",
    book: "احجز رحلتك",
    hero_line1: "تجاوز",
    hero_line2: "الطريق",
    hero_desc: "دراجات نارية. عربات التي جي. دراجات رباعية. صحراء واحدة مبنية للأدرينالين.",
    explore_rides: "استكشف الرحلات",
    explore: "استكشف",
    our_tours: "جولاتنا",
    our_packages: "باقاتنا",
    quick_links: "روابط سريعة",
    experiences: "التجارب",
    contact_us: "اتصل بنا",
    follow: "تابعنا",
    exp_1_title: "KTM 450CC",
    exp_1_sub: "دراجات احترافية",
    exp_2_title: "رحلات صحراوية موجهة",
    exp_2_sub: "مرشدون محليون خبراء",
    exp_3_title: "جميع المعدات متضمنة",
    exp_3_sub: "اركب بأمان. اركب بجرأة.",
    about_eyebrow: "قصتنا",
    about_title_1: "أكثر من",
    about_title_2: "رحلة.",
    about_title_3: "إنها",
    about_title_4: "مغامرة.",
    about_desc: "ولدت إندورو بايك دبي في صحراء دبي، وتم بناؤها حول فكرة بسيطة — تحويل كل رحلة إلى قصة تستحق التذكر.",
    about_loc: "صحراء البداير · دبي",
    about_btn: "اكتشف قصتنا",
    about_feat1_title: "ولد في دبي",
    about_feat1_sub: "جذور الصحراء.",
    about_feat2_title: "بنيت للمغامرة",
    about_feat2_sub: "أكثر من مجرد جولة.",
    about_feat3_title: "اركب بثقة",
    about_feat3_sub: "موجه. مجهز. مستعد."
  ,
    exp_eyebrow: "تجاربنا",
    exp_title_1: "مغامرات صحراوية ",
    exp_title_2: "لا تنسى",
    exp_desc: "اكتشف مجموعة من التجارب الصحراوية المثيرة.",
    exp_card1_title: "حجز سفاري صحراوي",
    exp_card1_desc: "استكشف حجز رحلات السفاري الصحراوية عبر الإنترنت.",
    exp_card1_cta: "اكتشف رحلات السفاري",
    exp_card2_title: "عربات الكثبان دبي",
    exp_card2_desc: "استعد لرحلة رائعة على الطرق الوعرة.",
    exp_card2_cta: "اكتشف رحلات الباغي",
    exp_card3_title: "دراجات نارية دبي",
    exp_card3_desc: "اركب عبر تضاريس الصحراء البرية في دبي.",
    exp_card3_cta: "اكتشف رحلات الدراجات",
    exp_card4_title: "دراجات رباعية دبي",
    exp_card4_desc: "اشعر بالإثارة مع الدراجات الرباعية القوية.",
    exp_card4_cta: "اكتشف رحلات الدراجات الرباعية",
    exp_card5_title: "سفاري صحراوي دبي",
    exp_card5_desc: "انغمس في جمال الصحراء العربية.",
    exp_card5_cta: "اكتشف السفاري",
    cta_eyebrow: "هل أنت مستعد",
    cta_title_1: "لقصتك ",
    cta_title_2: "التالية؟",
    cta_desc: "هل أنت مستعد لمغامرة لا تنسى؟ احجز رحلتك الآن.",
    cta_book: "احجز الآن",
    cta_hand_1: "نفس",
    cta_hand_2: "الصحراء.",
    cta_hand_3: "قصص",
    cta_hand_4: "مختلفة."
  ,
    packages_eyebrow: "اختر رحلتك",
    packages_title_1: "باقات",
    packages_title_2: "صحراوية",
    packages_title_3: "مميزة",
    packages_desc: "من الدراجات الترابية عالية السرعة إلى عربات الكثبان الرملية القوية والدراجات الرباعية، لدينا الآلة المثالية لمغامرتك التالية."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(languages[0]);

  // Translate function
  const t = (key) => {
    return translations[language.code]?.[key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, languages, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
